# Generated by Django 5.1.1 on 2024-12-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModeloGreenMarket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(blank=True, null=True, upload_to='media/producto_images/'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/proveedor_images/'),
        ),
    ]
